---
- hosts: localhost

  vars:
    aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('env','AWS_SECRET_KEY') }}"

  tasks:
  - name: launch ansible cloudformation example
    cloudformation:
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
      stack_name: "ansible-cloudformation"
      state: "present"
      region: "ap-southeast-2"
      disable_rollback: true
      template: "files/cloudformation-example.json"
      tags:
        Stack: "ansible-cloudformation"


